const GET_PRODUCTS = "GET_PRODUCTS";
const ADD_TO_CART = "ADD_TO_CART";
const UPDATE_CART = "UPDATE_CART";
const PRODUCT_DELETE = "PRODUCT_DELETE";
export { ADD_TO_CART, GET_PRODUCTS, PRODUCT_DELETE, UPDATE_CART };
